# Chem 274B: Software Engineering Fundamentals for
#            Molecular Sciences 
# 
# Creator:  Tony Drummond, PhD.  Faculty
# Date Created: September, 2022
# Date Updated: September 22, 2023
#
# Directory Path: Assignment2/Utils/Rangen
#
# This makefile creates object files from 2 C++ source files that
# implement random functions. One of the files was already used in 
# Week 5, and the other file contains new C++ utility functions 
# useful for testing hash functions and tables. After compiling the
# source C++ program files, it creates a random generator library 
# (libmyrandom.a), which is relocated to Assignment2/Utils/Lib after 
# its successful creation.

all: 
	cd Rangen; make all

